service: user-post-confirmation

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node24
    platform: node
    external:
      - '@aws-sdk/*'

custom:
  env: ${file(config/dev.yml)}
  serverless-offline:
    httpPort: 3005

provider:
  name: aws
  runtime: nodejs24.x
  environment: ${self:custom.env}

functions: ${file(config/functions.yml)}
